# Optional: uncomment to fix Rollup Linux binary when lockfile was created on another OS.
# [build.environment]
#   NPM_CONFIG_PLATFORM = "all"

[build]
  command = "npm run build"
  publish = "dist"
